name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]*'
  pull_request:
  repository_dispatch:
    types:
      - case_updated
      - cgmes_gl_updated

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout case client
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-case
          ref: refs/heads/main

      - name: Build and install case client with Maven
        run: mvn --batch-mode -DskipTests=true --file ../powsybl-case/case-datasource/pom.xml install

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Build with Maven
        run: mvn --batch-mode -Pjacoco install

      - name: Run SonarCloud analysis
        run: >
          mvn --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=gridsuite
          -Dsonar.projectKey=org.gridsuite:cgmes-gl-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image - Main
        if: github.ref == 'refs/heads/main'
        run: >
          mvn --batch-mode deploy -DskipTests -Dmaven.install.skip -Dmaven.deploy.skip -Dpowsybl.docker.deploy
          -Djib.httpTimeout=60000
          -Djib.to.image=docker.io/gridsuite/cgmes-gl-server
          -Djib.to.auth.username=gridsuiteci
          -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image - Tag
        if: startsWith(github.ref, 'refs/tags/')
        run: >
          mvn --batch-mode deploy -DskipTests -Dmaven.install.skip -Dmaven.deploy.skip -Dpowsybl.docker.deploy
          -Djib.httpTimeout=60000
          -Djib.to.image=docker.io/gridsuite/cgmes-gl-server:${GITHUB_REF_NAME#v}
          -Djib.to.auth.username=gridsuiteci
          -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }}

      - name: Broadcast update event
        if: github.ref == 'refs/heads/main'
        uses: gridsuite/broadcast-event@main
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: cgmes_gl_server_updated
